name: Build and deploy JAR app to staging
on:
  push:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn clean install
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bankingbh
          path: '${{ github.workspace }}/target/*.jar'
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bankingbh
          path: '${{ github.workspace }}/target/'
          
      - name: Install SSHPASS
        run: sudo apt-get install -y sshpass
          
      - name: Deploy to Staging
        run: |
          ssh-keyscan -H ${{ secrets.VPS_CONNECTION }} >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.VPS_PASS }}" scp ${{ github.workspace }}/target/bankingbh-1.0-SNAPSHOT.jar ${{ secrets.VPS_CONNECTION }}:/bankingbh/
        env:
          SSHPASS: ${{ secrets.VPS_PASS }}
